name: Portfolio CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: npm install

      - run: npx playwright install --with-deps

      - run: npm test

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Create GitHub Issue
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Portfolio Test Failure
          content-filepath: issue.md
